const db = require('../db')
const { Brand,Category,Product } = require('../models')

const createProducts = async() => {
    const tShirts = await Category.find({ name: 'T-Shirts', gender:'Neutral' })
    const tShirtsWomen = await Category.find({ name: 'T-Shirts', gender:'Women' })
    const longsleeves = await Category.find({ name: 'Longsleeves', gender: 'Neutral' })
    const longsleevesWomen = await Category.find({ name: 'Longsleeves', gender: 'Women' })
    const hoodies = await Category.find({ name: 'Hoodies', gender: 'Neutral' })
    const crewneck = await Category.find({ name: 'Crewnecks', gender: 'Neutral' })
    const dresses = await Category.find({ name: 'Dresses', gender: 'Women' })

    const happyEarthApparel = await Brand.find({ name: 'Happy Earth Apparel' })
    const mpgSport = await Brand.find({ name: 'MPG Sport' })
    const products = [
        {
            name: 'California Poppies',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/california-poppies'),
            price: 32,
            color: 'Black',
            size: 'M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/ig2_1080x.jpg?v=1682019038'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/ig1_1080x.jpg?v=1682019038')
        },
        {
            name: 'Tree of Life',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/tree-of-life'),
            price: 32,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2452_1x1_972eef78-e39c-45de-8596-f54f10b11725_1080x.jpg?v=1683224431'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2453_1x1_835e4699-d7ef-419b-bcfd-e21babe5eb68_1080x.jpg?v=1683224339')
        },
        {
            name: 'Summer Waves',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/summer-waves'),
            price: 32,
            color: 'Green',
            size: 'S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_1853_gray_1080x.jpg?v=1686761078')
        },
        {
            name: 'Make Waves',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/make-waves'),
            price: 32,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1860_gray_1x1_253d3914-e4b8-404f-a17a-2f255e075265_1080x.jpg?v=1681138408'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1856_gray_1x1_86e04f66-d5cd-4d3e-8f64-13de4fcd521b_1080x.jpg?v=1681138293')
        },
        {
            name: 'Sea Turtles',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/sea-turtles'),
            price: 32,
            color: 'Green',
            size: 'XS, S, M, L, XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1883_gray_1x1_e421a43d-2ca5-4a01-8b4a-0d31827454c4_1080x.jpg?v=1681141505'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1882_gray_1x1_e590ad19-fea5-4b99-a8fe-8a5c7f907b06_1080x.jpg?v=1681141504')
        },
        {
            name: 'Day and Night',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/day-and-night'),
            price: 32,
            color: 'Tan',
            size: 'S, M, L, XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://www.happyearthapparel.com/cdn/shop/files/IMG_1861_gray.jpg?v=1686760874&width=1600'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1861_gray_1x1_ea22112d-e186-4fd7-9985-50c7fdb9c4a5_1080x.jpg?v=1681138651'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/p5_1080x.jpg?v=1682019081')
        },
        {
            name: 'Cosmos',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/cosmos'),
            price: 32,
            color: 'Black',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://www.happyearthapparel.com/cdn/shop/files/IMG_1879_gray.jpg?v=1686760859&width=1800'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1879_gray_1x1_f94daf8c-540e-44f1-83fe-f9c12ea27309_1080x.jpg?v=1681139618'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/p7_1080x.jpg?v=1682019102')
        },
        {
            name: 'Heat Waves',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/heat-waves'),
            price: 32,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2452_1x1_d8614776-e240-40e7-a9dc-88dd353ea982_1080x.jpg?v=1683224867'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2454_1x1_faddfb5a-b67d-476c-9453-4d91828f8bc3_1080x.jpg?v=1683224867')
        },
        {
            name: 'Peace',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/peace'),
            price: 32,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_1888_gray_1080x.jpg?v=1686761007')
        },
        {
            name: 'Protect Our Oceans',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/protect-our-oceans'),
            price: 32,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_1863_gray_1080x.jpg?v=1686761028'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1864_gray_1x1_4b25458c-b5e6-4405-8b2e-470564339134_1080x.jpg?v=1686761028')
        },
        {
            name: 'Flower Garden',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/flower-garden-ss'),
            price: 32,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_1884_gray_d8985f86-f773-449f-9143-49cc350fb645_1080x.jpg?v=1686760947')
        },
        {
            name: 'Dawn Patrol',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/dawn-patrol'),
            price: 32,
            color: 'Blue',
            size: 'M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/DawnPatrol_web_1080x.jpg?v=1686759081'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/dawn-patrol-506314_1080x.jpg?v=1686759081'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/dawn-patrol-749953_1080x.jpg?v=1686759081')
        },
        {
            name: 'Mer Polaire',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/mer-polaire'),
            price: 32,
            color: 'Blue',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/mer-polaire-418226_1080x.jpg?v=1686759175'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/MerPolaire_web_1080x.jpg?v=1686759175'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/mer-polaire-581564_1080x.jpg?v=1686759191')
        },
        {
            name: "Sirius' Howl",
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/sirius-howl'),
            price: 32,
            color: 'Blue',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SiriusHowl_web_1080x.jpg?v=1686759403'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sirius-howl-481351_1080x.jpg?v=1686759403'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sirius-howl-897754_1080x.jpg?v=1686759403')
        },
        {
            name: 'Teton Bison',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/teton-bison'),
            price: 32,
            color: 'Blue',
            size: 'S, M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A super-soft cotton knit and relaxed fit Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/TetonBison_web_1080x.jpg?v=1686759586'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/teton-bison-761520_1080x.jpg?v=1686759586')
        },
        {
            name: 'Yukon Bull',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/yukon-bull'),
            price: 32,
            color: 'Green',
            size: 'S, M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/YukonBull_web_1080x.jpg?v=1686759741'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/yukon-bull-496852_1080x.jpg?v=1686759741'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/yukon-bull-614181_1080x.jpg?v=1686759757')
        },
        {
            name: 'Arboretum',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/arboretum'),
            price: 29,
            color: 'Green',
            size: 'S, M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Arboretum_web_900x.jpg?v=1686758985'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/arboretum-417524_1080x.jpg?v=1686758985'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/arboretum-911023_1080x.jpg?v=1686758985')
        },
        {
            name: 'Sentinel',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/sentinel'),
            price: 29,
            color: 'Green',
            size: 'M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Sentinel_web_1080x.jpg?v=1686759248'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sentinel-837975_1080x.jpg?v=1686759248'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sentinel-589182_1080x.jpg?v=1686759248')
        },
        {
            name: 'Premium-Weight Tee | Calathea Green',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/premium-weight-tee-calathea-green'),
            price: 44,
            color: 'Green',
            size: 'S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Thick yet airy, and ultra-soft. A super-high quality short sleeve tee that perfectly balances a premium, heavy weight with flow and breathability. Thin stripes are meticulously woven throughout the fabric for an elegant and elevated style.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/1_c47b7f75-e760-432e-837c-ea771edf351e_1080x.jpg?v=1681827634'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1988_1x1_ad59696c-dd9f-444e-bcc7-2aa4ee4c9603_1080x.jpg?v=1681827634'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/P2_1080x.jpg?v=1682019205')
        },
        {
            name: 'Premium-Weight Tee | Beech Wood',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/premium-weight-tee-beech-wood'),
            price: 44,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Thick yet airy, and ultra-soft. A super-high quality short sleeve tee that perfectly balances a premium, heavy weight with flow and breathability. Thin stripes are meticulously woven throughout the fabric for an elegant and elevated style.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/t1_cbb59613-c608-437a-ba51-960e745f68ec_1080x.jpg?v=1681835899'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1991_1x1_cd7f8fee-7cee-45f5-a2c0-5ff51efc85bd_1080x.jpg?v=1681845772'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_2077_1x1_feb5e882-754c-414b-9727-3458f14508fa_1080x.jpg?v=1681845772')
        },
        {
            name: 'Better Basics: Organic Short Sleeve Tee',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-short-sleeve-tee'),
            price: 25,
            color: 'Green',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Green_web_1080x.jpg?v=1686760043')
        },
        {
            name: 'Better Basics: Organic Short Sleeve Tee',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-short-sleeve-tee'),
            price: 25,
            color: 'Blue',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Slate_web_1080x.jpg?v=1686760038')
        },
        {
            name: 'Better Basics: Organic Short Sleeve Tee',
            category: tShirts[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-short-sleeve-tee'),
            price: 25,
            color: 'Black',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Black_web_1080x.jpg?v=1686760033')
        },
        {
            name: 'Better Basics: Womens Green Short Sleeve Tee',
            category: tShirtsWomen[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/better-basics-womens-green-short-sleeve-tee'),
            price: 24,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed to be part of your regular rotation. A fitted, ultra-soft organic cotton tee that's great for everyday wear.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/WomensGreenBlank_web_1080x.jpg?v=1686760107')
        },
        {
            name: 'Kind Words Wild Places',
            category: tShirtsWomen[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/kind-words-womens-tee'),
            price: 15,
            color: 'White',
            size: 'S, M',
            inStock: true,
            description: "Designed to be part of your regular rotation. A fitted, ultra-soft organic cotton tee that's great for everyday wear.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/KindWords_web_1080x.jpg?v=1686761338'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/kind-words-wild-places-393542_1080x.jpg?v=1686761338')
        },
        {
            name: 'Sequoia',
            category: tShirtsWomen[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/sequoia-womens-tee'),
            price: 15,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed to be part of your regular rotation. A fitted, ultra-soft organic cotton tee that's great for everyday wear.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Sequoia_web_1080x.jpg?v=1686761161'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sequoia-347167_1080x.jpg?v=1686761161')
        },
        {
            name: 'Wild',
            category: tShirtsWomen[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/wild-womens-tee'),
            price: 19,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed to be part of your regular rotation. A fitted, ultra-soft organic cotton tee that's great for everyday wear.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/wild-146993_1080x.jpg?v=1659914827'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/wild-398024_1080x.jpg?v=1659914827')
        },
        {
            name: 'Cacao Tree | Alter Eco x Happy Earth',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/cacao-tree-altereco-x-happy-earth'),
            price: 38,
            color: 'Green',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/1101008AlterEcoCacaoTree-3_1080x.jpg?v=1680199843'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/1101008AlterEcoCacaoTree-2_1080x.jpg?v=1680199843'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/1101008AlterEcoCacaoTree-1_1080x.jpg?v=1680199843')
        },
        {
            name: 'Half Dome',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/half-dome'),
            price: 38,
            color: 'Green',
            size: 'S, M, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/half-dome-916568_1080x.jpg?v=1686750885'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/HalfDome_web_1080x.jpg?v=1686750885'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/half-dome-191663_1080x.jpg?v=1686750885')
        },
        {
            name: 'Solstice Fir',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/solstice-fir'),
            price: 38,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/solstice-fir-organic-long-sleeve-tee-happy-earth-apparel-490122_1080x.jpg?v=1686757133'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SolsticeFir_web_1080x.jpg?v=1686757133')
        },
        {
            name: 'Supernal Nyx',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/supernal-nyx'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SupernalNyx_web_1080x.jpg?v=1686757192'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/supernal-nyx-139580_1080x.jpg?v=1686757192'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/supernal-nyx-905268_1080x.jpg?v=1686757192')
        },
        {
            name: 'Golden Mountains',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/golden-mountains'),
            price: 38,
            color: 'Black',
            size: 'XS, S, M, L, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://www.happyearthapparel.com/cdn/shop/files/IMG_7919_web.jpg?v=1692804368&width=1600'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/golden-mountains-organic-long-sleeve-tee-happy-earth-apparel-713003_1080x.jpg?v=1686750807')
        },
        {
            name: 'Costa Rica Sunshine',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/costa-rica-sunshine'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/CostaRicaSunshine_web_1080x.jpg?v=1686750046'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/costa-rica-sunshine-organic-long-sleeve-tee-happy-earth-apparel-135838_1080x.jpg?v=1686750046')
        },
        {
            name: 'Lunar Glow',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/lunar-glow'),
            price: 38,
            color: 'Blue',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/LunarGlow_web_1080x.jpg?v=1686751094'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/lunar-glow-991422_1080x.jpg?v=1686751094'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/lunar-glow-756278_1080x.jpg?v=1686751094')
        },
        {
            name: 'Laniakea Beach',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/laniakea-beach'),
            price: 38,
            color: 'Blue',
            size: 'S, M',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/LaniakeaBeach_web_1080x.jpg?v=1686750972'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/laniakea-beach-organic-long-sleeve-tee-happy-earth-apparel-417908_1080x.jpg?v=1686750972'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/laniakea-beach-organic-long-sleeve-tee-happy-earth-apparel-106562_1080x.jpg?v=1686750972')
        },
        {
            name: 'Midnight Woods',
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/midnight-woods'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/MidnightWoods_web_1080x.jpg?v=1686751193'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/midnight-woods-244502_1080x.jpg?v=1686751193'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/midnight-woods-965508_1080x.jpg?v=1686751193')
        },
        {
            name: "Winter's Call",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/winters-call'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/WintersCall_web_1080x.jpg?v=1686757260'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/winters-call-516038_1080x.jpg?v=1686757260'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/winters-call-346064_1080x.jpg?v=1686757260')
        },
        {
            name: "Ours Polaire",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/ours-polaire'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, L, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/OursPolaire_web_1080x.jpg?v=1686756873'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/ours-polaire-502690_1080x.jpg?v=1686756873'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/ours-polaire-592482_1080x.jpg?v=1686756873')
        },
        {
            name: "Forest Guardian",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/forest-guardian'),
            price: 38,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/ForestGuardian_web_1080x.jpg?v=1686750168'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-guardian-759298_1080x.jpg?v=1686750168'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-guardian-639366_1080x.jpg?v=1686750168')
        },
        {
            name: "Forest Happy Earth Logo",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/happy-earth-logo-green'),
            price: 38,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/HappyEarthLogoForest_web_1080x.jpg?v=1686750408'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-happy-earth-logo-320464_1080x.jpg?v=1686750408'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-happy-earth-logo-844727_1080x.jpg?v=1686750408')
        },
        {
            name: "Prescripta Silva",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/perscripta-silva'),
            price: 38,
            color: 'Green',
            size: 'S, M, L, XL, 2XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/PerscriptaSilva_web_1080x.jpg?v=1686756929'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/perscripta-silva-774261_1080x.jpg?v=1686756929'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/perscripta-silva-578470_1080x.jpg?v=1686756929')
        },
        {
            name: "Abnoba Mons",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/abnoba-mons'),
            price: 38,
            color: 'Black',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/AbnobaMons_web_1e2b37b5-ae7b-4c62-af60-fb091859a2b6_1080x.jpg?v=1686749957'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/abnoba-mons-313924_1080x.jpg?v=1686749957'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/abnoba-mons-139985_1080x.jpg?v=1686749957')
        },
        {
            name: "Sand Dune Sunrise",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/sand-dune-sunrise'),
            price: 38,
            color: 'Black',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SandDuneSunrise_web_1080x.jpg?v=1686757002'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sand-dune-sunrise-659647_1080x.jpg?v=1686757002')
        },
        {
            name: "Snow Fir",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/snow-fir'),
            price: 38,
            color: 'Green',
            size: 'XS, S, M, L',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SnowFir_web_1080x.jpg?v=1686757074')
        },
        {
            name: "Better Basics: Organic Long Sleeve Tee",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-long-sleeve-tee'),
            price: 28,
            color: 'Black',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Black_LS_web_1080x.jpg?v=1686760482')
        },
        {
            name: "Better Basics: Organic Long Sleeve Tee",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-long-sleeve-tee'),
            price: 28,
            color: 'Green',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Green_LS_web_1080x.jpg?v=1686760489')
        },
        {
            name: "Better Basics: Organic Long Sleeve Tee",
            category: longsleeves[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/shirts/products/organic-long-sleeve-tee'),
            price: 28,
            color: 'Blue',
            size: 'S, M, L, XL',
            inStock: true,
            description: "Designed for comfort in all of life's adventures. A relaxed, ultra-soft organic cotton tee that's great for everyday wear: your go-to worry-free style that's made to live-in.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Navy_LS_web_1080x.jpg?v=1686760537')
        },
        {
            name: "Fading Forest Hoodie",
            category: hoodies[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/fading-forest-hoodie'),
            price: 68,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL, 3XL, 4XL',
            inStock: true,
            description: "Relaxed, oversized hoodie with large hood and forest pocket panel design. Ditch the polyester sweatshirts, and upgrade in sustainability and style. This two-toned hoodie in dark green and beige is a unique addition to any wardrobe.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/FadingForestHoodie_updated_1080x.jpg?v=1683212855'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/logo_1_900x.jpg?v=1685459524'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/logo_3_900x.jpg?v=1685459524')
        },
        {
            name: "Full Zip Herringbone Flex Hoodie | Calathea Green",
            category: hoodies[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/full-zip-calathea-green'),
            price: 88,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Your warm-weather basics – upgraded. The distinctive zigzag weave of our herringbone collection elevates a typical, flat fabric. And not just an aesthetic win, these knits are breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this fabric has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_2091_3x4_b95f276d-b369-4a0a-a2d5-e649cb1e45a8_1080x.jpg?v=1682296128'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/6_2984c26d-8119-44aa-9221-3a5bb1fb2ace_1080x.jpg?v=1682296128'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/2_c43d8bdd-c279-4aed-a7db-c562200d6992_1080x.jpg?v=1682296128')
        },
        {
            name: "Full Zip Herringbone Flex Hoodie | Deep Sea",
            category: hoodies[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/full-zip-deep-sea'),
            price: 88,
            color: 'Blue',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Your warm-weather basics – upgraded. The distinctive zigzag weave of our herringbone collection elevates a typical, flat fabric. And not just an aesthetic win, these knits are breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this fabric has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_2096_3x4_aecfd73f-d5fa-4e7c-9f4f-6afd3094691b_1080x.jpg?v=1682296067'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/bh2_900x.jpg?v=1682296067'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_2105_3x4_8c7272f1-4f15-43f4-a40d-9f32f774118d_1080x.jpg?v=1682296067')
        },
        {
            name: "Full Zip Herringbone Flex Hoodie | Beech Wood",
            category: hoodies[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/full-zip-beech-wood'),
            price: 88,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Your warm-weather basics – upgraded. The distinctive zigzag weave of our herringbone collection elevates a typical, flat fabric. And not just an aesthetic win, these knits are breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this fabric has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2043_3x4_7628fea8-f6da-40ca-b902-f65d81dc9ecf_1080x.jpg?v=1682438445'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/3_533d9ad5-4f5f-417d-9c91-c43e2ceb44b0_1080x.jpg?v=1682438445'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/IMG_2114_3x4_1ef477dc-3d3c-45fd-aee3-b03242243c84_1080x.jpg?v=1682438445')
        },
        {
            name: "Poppies Herringbone Flex Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/poppies-herringbone-flex-crew'),
            price: 68,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "A warm-weather basic, upgraded. The distinctive herringbone pattern elevates the color and body of this crew, and is woven to be breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this crew has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/poppies1_1080x.jpg?v=1687467535'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Crew_CaliPoppies_1080x.jpg?v=1687467535'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/1_555678fe-ba09-4ebe-a847-54c680d44c27_1080x.jpg?v=1687467535')
        },
        {
            name: "Happy Earth Script Herringbone Flex Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/script-herringbone-flex-crew'),
            price: 68,
            color: 'Green',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "A warm-weather basic, upgraded. The distinctive herringbone pattern elevates the color and body of this crew, and is woven to be breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this crew has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://www.happyearthapparel.com/cdn/shop/files/herringbone.jpg?v=1692837807&width=1600'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/navy2_1080x.jpg?v=1687467512'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/IMG_1993_1x1_d89f8d81-daa4-44fb-856e-cef375bd117d_1080x.jpg?v=1687467512')
        },
        {
            name: "Sunset Herringbone Flex Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/sunset-herringbone-flex-crew'),
            price: 68,
            color: 'Tan',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "A warm-weather basic, upgraded. The distinctive herringbone pattern elevates the color and body of this crew, and is woven to be breathable, soft, and stretchy. Made from organic cotton with a touch of elastane, this crew has a natural, fluid drape and easily adapts to movement.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/sun1_1080x.jpg?v=1687467586'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/Crew_Sunset_1080x.jpg?v=1687467939'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/2_489f746f-1afe-4e85-94d5-bcb20bfa5676_1080x.jpg?v=1687467939')
        },
        {
            name: "Stormy Forest Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/stormy-forest-crew'),
            price: 64,
            color: 'Black',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Soft and sustainable, Fair Trade Organic Cotton ensures it's good for people and the planet. Ditch the plastic polyester sweatshirts, and upgrade in sustainability and style.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/StormyForestCrew3x4_1080x.jpg?v=1683311515'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/stormy-forest-crew-531058_900x.jpg?v=1683311515'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/stormy-forest-crew-495544_1080x.jpg?v=1683311515')
        },
        {
            name: "Sentinel Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/sentinel-fleece-crew'),
            price: 48,
            color: 'Green',
            size: 'S, M',
            inStock: true,
            description: "Soft and sustainable, Fair Trade Organic Cotton ensures it's good for people and the planet. Ditch the plastic polyester sweatshirts, and upgrade in sustainability and style.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/SentinelGreen2_web_900x.jpg?v=1686761989'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sentinel-crew-629584_1080x.jpg?v=1686761989'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/sentinel-crew-407287_1080x.jpg?v=1686761989')
        },
        {
            name: "Rolling Seas Crew",
            category: crewneck[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/sweatshirts/products/rolling-seas-fleece-crew'),
            price: 36,
            color: 'Blue',
            size: 'XS',
            inStock: true,
            description: "Soft and sustainable, Fair Trade Organic Cotton ensures it's good for people and the planet. Ditch the plastic polyester sweatshirts, and upgrade in sustainability and style.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/RollingSeas_web_1080x.jpg?v=1686761946'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/rolling-seas-crew-191915_1080x.jpg?v=1686761946'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/rolling-seas-crew-225766_1080x.jpg?v=1686761946')
        },
        {
            name: "Monstera Ruffle Wrap Dress",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/ruffle-wrap-dress'),
            price: 88,
            color: 'Green',
            size: 'X/XS, S/M, M/L, 2XL/3XL',
            inStock: true,
            description: "*May Cause Dancing* Made from a combination of soft, breathable organic cotton and naturally stretchy Tencel, it has a premium luxe feel that'll make you want to move. Weddings, happy hours, beach trips, and backyard BBQs — we hate to play favorites — but it's the only dress you'll need this season (or decade).",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/dress1_1080x.jpg?v=1687467465'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/dress2_1080x.jpg?v=1687467465'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Neck_1_1080x.jpg?v=1687467465')
        },
        {
            name: "Forest Flow Organic T-Shirt Dress",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/ruffle-wrap-dress'),
            price: 54,
            color: 'Grey',
            size: 'S, M, L',
            inStock: true,
            description: "Your favorite tee - in dress form. Effortlessly chic with its relaxed, flattering fit. Fun to wear and easy to layer, we give the classic t-shirt dress a radical upgrade in sustainability and style. Heather charcoal gray and made with medium-weight organic cotton jersey for the perfect balance of structure and flow.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/forest_75adb0c9-f315-47bf-a163-9711d527d1b0_1080x.jpg?v=1682694890'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-flow-organic-t-shirt-dress-organic-dress-happy-earth-apparel-921029_1080x.jpg?v=1682694890'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/forest-flow-organic-t-shirt-dress-organic-dress-happy-earth-apparel-429326_1080x.jpg?v=1682694890')
        },
        {
            name: "Black Organic T-Shirt Dress",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/black-organic-t-shirt-dress'),
            price: 54,
            color: 'Black',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Your favorite tee - in dress form. Effortlessly chic with its relaxed, flattering fit. Fun to wear and easy to layer, we give the classic t-shirt dress a radical upgrade in sustainability and style. Heather charcoal gray and made with medium-weight organic cotton jersey for the perfect balance of structure and flow.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/black1_1080x.jpg?v=1682694936'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/blac2_1080x.jpg?v=1682694945'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/black-organic-t-shirt-dress-organic-dress-happy-earth-apparel-699622_1080x.jpg?v=1682694936')
        },
        {
            name: "Petit Jardin Organic T-Shirt Dress",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/petit-jardin-t-shirt-dress'),
            price: 54,
            color: 'Black',
            size: 'XS, S, M, L',
            inStock: true,
            description: "Your favorite tee - in dress form. Effortlessly chic with its relaxed, flattering fit. Fun to wear and easy to layer, we give the classic t-shirt dress a radical upgrade in sustainability and style. Heather charcoal gray and made with medium-weight organic cotton jersey for the perfect balance of structure and flow.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/flower_900x.jpg?v=1682694915'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/petit-jardin-organic-t-shirt-dress-organic-dress-happy-earth-apparel-661286_1080x.jpg?v=1682694915'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/petit-jardin-organic-t-shirt-dress-organic-dress-happy-earth-apparel-457167_1080x.jpg?v=1682694915')
        },
        {
            name: "Black Organic Fit + Flare Midi Dress",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/black-fit-flare-midi'),
            price: 64,
            color: 'Black',
            size: 'XS, S, M, L, XL, 2XL, 3XL',
            inStock: true,
            description: "Fitted top, elegant v-neck, long sleeves and flowy skirt - this midi style cuts a classic silhouette. Made from premium organic cotton, this dress is the very picture of versatility and style. It's the LBD every closet needs.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/files/fitflare_1080x.jpg?v=1682694968'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/black-organic-fit-flare-midi-dress-organic-dress-happy-earth-apparel-944433_1080x.jpg?v=1682694968'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/black-organic-fit-flare-midi-dress-organic-dress-happy-earth-apparel-596210_1080x.jpg?v=1682694968')
        },
        {
            name: "PlantTec™ Reversible Dress | Eclipse",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/planttec-reversible-dress-eclipse'),
            price: 98,
            color: 'Black',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Structured support where you want it, stretchy comfort where you need it. This 2-piece bundle combines a reversible dress with matching shorts for comfort and ease. Thoughtfully designed to be worn in two ways, this dress is a two-for-one style gem featuring both a classic jewel and square neck.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Black_Pocket_2_fef06967-b30f-4097-8360-0acf43702e0d_1080x.jpg?v=1684354544'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Black_HighNeck_Back_1_2bdc3b64-883f-4706-a69e-0b0e9bab647d_1080x.jpg?v=1684354544'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Black_HighNeck_Front_3_5e886567-bc29-4594-b7cf-b599a669e78c_1080x.jpg?v=1684354544')
        },
        {
            name: "PlantTec™ Reversible Dress | Monstera",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/planttec-reversible-dress-eclipse'),
            price: 98,
            color: 'Blue',
            size: 'XXS, XS, S, M, L, XL',
            inStock: true,
            description: "Structured support where you want it, stretchy comfort where you need it. This 2-piece bundle combines a reversible dress with matching shorts for comfort and ease. Thoughtfully designed to be worn in two ways, this dress is a two-for-one style gem featuring both a classic jewel and square neck.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Monsterra_HighNeck_Front_3_62ac271c-86ac-4750-aef6-5ae2713bcb7e_1080x.jpg?v=1680647711'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Monsterra_HighNeck_Front_1_ae030f7b-6bd7-416f-b383-7ed11062d035_1080x.jpg?v=1680647711'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Monsterra_SquareNeck_Back_9cb07381-3c24-4b23-86c9-092aca39043f_1080x.jpg?v=1680647711')
        },
        {
            name: "PlantTec™ Reversible Dress | Sage",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/planttec-reversible-dress-sage'),
            price: 98,
            color: 'Green',
            size: 'XXS, XS, S, M, L, XL',
            inStock: true,
            description: "Structured support where you want it, stretchy comfort where you need it. This 2-piece bundle combines a reversible dress with matching shorts for comfort and ease. Thoughtfully designed to be worn in two ways, this dress is a two-for-one style gem featuring both a classic jewel and square neck.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sage_Pocket_1_d5f2327f-8e4e-41c6-8fac-8c61eaec018d_1080x.jpg?v=1680575421'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sage_SquareNeck_Front_2_dbf3094f-5025-4083-a3e6-0c35f2ceb36a_1080x.jpg?v=1680615335'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sage_SquareNeck_Back_1_7841c6ed-eca2-4bfe-8613-573905b6fcf8_1080x.jpg?v=1680615335')
        },
        {
            name: "PlantTec™ Reversible Dress | Sandstone",
            category: dresses[0]._id,
            brand: happyEarthApparel[0]._id,
            link: new URL('https://www.happyearthapparel.com/collections/dresses/products/planttec-reversible-dress-sandstone'),
            price: 98,
            color: 'Tan',
            size: 'XXS, XS, S, M, L, XL',
            inStock: true,
            description: "Structured support where you want it, stretchy comfort where you need it. This 2-piece bundle combines a reversible dress with matching shorts for comfort and ease. Thoughtfully designed to be worn in two ways, this dress is a two-for-one style gem featuring both a classic jewel and square neck.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sand_Pocket_1_e2c13b35-3e9b-4753-84b8-08f9d9f24b24_1080x.jpg?v=1680575638'),
            image2: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sand_SquareNeck_Front_2_b8496eb0-cb90-4513-b631-0f56909087f1_1080x.jpg?v=1680614985'),
            image3: new URL('https://cdn.shopify.com/s/files/1/0272/1500/3781/products/Sand_SquareNeck_Back_2_b751700d-4ff7-4858-9898-5f5692d8cacf_1080x.jpg?v=1680614985')
        },
        {
            name: 'Dynamic Recycled Stink-Free Sleeveless Top',
            category: tShirtsWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/dynamic-recycled-anti-stink-sleeveless-top'),
            price: 34,
            color: 'Red',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "You're a dynamo. Anti-stink technology works to nix odour so that you can wear this top on repeat. Throw it on as a cover-up post-workout or on its own for an on-trend everyday look. Now available in recycled fabric.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0509-C0613-1_800x.jpg?v=1679325178'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0509-C0613-3_800x.jpg?v=1679325178'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0509-C0613-4_800x.jpg?v=1679325178')
        },
        {
            name: 'Dynamic Recycled Polyester Relaxed Short Sleeve T- Shirt',
            category: tShirtsWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/dynamic-relaxed-short-sleeve-t-shirt'),
            price: 42,
            color: 'Red',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "You’re a dynamo. Relaxed, oversized, boxy… whichever way you want to describe it, the look is on fire, and this t-shirt captures the essence of the trend perfectly.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0920-C0613-1_800x.jpg?v=1675037686'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0920-C0613-3_800x.jpg?v=1675037686'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0920-Dynamic-SS-Tee-Cardinal_800x.jpg?v=1676665496')
        },
        {
            name: 'Calm Short Sleeve T-Shirt',
            category: tShirtsWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/calm-short-sleeve-t-shirt'),
            price: 44,
            color: 'Black',
            size: 'XS, S, M, L, XL, 2XL',
            inStock: true,
            description: "Turn down the noise. And share your Pride or show your support for the LGBTQ community in this cut-out tee made for maximum comfort while you’re on the go.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/files/11M0006-1401-1_800x.jpg?v=1685718609'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/files/11M0006-1401-3_800x.jpg?v=1685718609'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/files/11M0006-1401-7_800x.jpg?v=1685731831')
        },
        {
            name: 'Dynamic Recycled Cover-Up Stink-Free Long Sleeve Top',
            category: longsleevesWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/dynamic-recycled-cover-up-anti-stink-long-sleeve-top'),
            price: 30,
            color: 'Green',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "You're a dynamo. This recycled fabric is made with anti-stink technology to go longer between washes. (The planet and your water bill will thank you.)",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0514-C0623-1_800x.jpg?v=1675286891'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0514-C0623-3_800x.jpg?v=1675286891'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0514-C0623-6_800x.jpg?v=1675286891')
        },
        {
            name: 'Calm Relaxed Top',
            category: tShirtsWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/calm-relaxed-top'),
            price: 38,
            color: 'Blue',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Turn down the noise. And shift into slower gear in this relaxed and cropped top with an on-trend, oversized silhouette. This is laid-back, uber-cool style for those who want to look good in chill mode.",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0914-2623-1_800x.jpg?v=1674775556'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0914-2623-4_800x.jpg?v=1674775556'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A0914-Calm-Tshirt-cobalt_800x.jpg?v=1676665497')
        },
        {
            name: 'Pace Sliced Front Long Sleeve Top',
            category: longsleevesWomen[0]._id,
            brand: mpgSport[0]._id,
            link: new URL('https://mpgsport.com/collections/womens-t-shirts/products/pace-sliced-front-long-sleeve-top'),
            price: 54,
            color: 'White',
            size: 'XS, S, M, L, XL',
            inStock: true,
            description: "Find your rhythm. Pair this super soft top featuring an on-trend sliced opening with oversized cargo or wide-leg pants for a look that says, “I’m street tough, but I also enjoy being comfy.”",
            mainImage: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A1013-1171-1_800x.jpg?v=1674775512'),
            image2: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A1013-1171-4_800x.jpg?v=1674775512'),
            image3: new URL('https://cdn.shopify.com/s/files/1/2785/1604/products/11A1013-1171-3_800x.jpg?v=1674775512')
        }
    ]
    await Product.insertMany(products)
    console.log('added products')
}

const run = async() => {
    await createProducts()
    db.close()
}

run()